Operational procedures
wireapp/wire-docs pull request #208
Opened 2021-08-30 18:30 UTC by arthurwolf

(fill in your PR description)

## Checklist:

Please tick the following before making your PR:

* [x] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [x] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.

2021-08-30 18:31 UTC, arthurwolf commented
Preview for reference:

![Screenshot_2021-08-30 Operational procedures — Wire documentation](https://user-images.githubusercontent.com/108821/131387384-4e891c7a-bb4a-44d5-bf0c-37a76d8c81aa.png)

2021-08-30 18:32 UTC, arthurwolf commented
Screenshot of current render for reference:

![Screenshot_2021-08-30 Operational procedures — Wire documentation(1)](https://user-images.githubusercontent.com/108821/131387504-90c3f240-575a-4016-8cf3-4d55b43f4a8b.png)

2021-08-30 19:28 UTC, jschaul requested changes
There are some existing pages for the different kinds of servers here: https://github.com/wireapp/wire-docs/tree/master/src/how-to/administrate

I think the information in this PR and the information in those pages should be combined into the same pages.

2021-08-31 14:09 UTC, arthurwolf commented
Render of most recent version (with the health checks moved to the separate per-pod sections), for reference:

![Screenshot from 2021-08-31 16-08-34](https://user-images.githubusercontent.com/108821/131517677-cd0f7689-974d-4afb-90e2-4b6c4d0370ac.png)

2021-08-31 15:26 UTC, arthurwolf commented
Note: @arianvp mentionned https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

2021-08-31 15:26 UTC, arthurwolf commented
Note: Maybe it would make sense to add instructions for fluent-bit health checking, which can be found at https://docs.fluentbit.io/manual/administration/monitoring

2021-08-31 19:43 UTC, arthurwolf commented
Some more current renders for reference:

![Screenshot_2021-08-31 Restund (TURN) — Wire documentation](https://user-images.githubusercontent.com/108821/131565950-0fb8daf8-81e9-4f7a-b6d9-53dc1ac76027.png)
![Screenshot_2021-08-31 Minio — Wire documentation](https://user-images.githubusercontent.com/108821/131565953-290815a6-4ec6-4a37-9b7f-ef3eb563a808.png)
![Screenshot_2021-08-31 Elasticsearch — Wire documentation(1)](https://user-images.githubusercontent.com/108821/131565956-a0fe003b-af02-426b-8193-17938a4d2799.png)
![Screenshot_2021-08-31 Elasticsearch — Wire documentation](https://user-images.githubusercontent.com/108821/131565957-555f4fe0-2ebe-4a46-8530-c6212ce8e9e1.png)
![Screenshot_2021-08-31 Cassandra — Wire documentation](https://user-images.githubusercontent.com/108821/131565961-f7d1377d-1cf2-49df-829b-f4b217eb2c4c.png)

2021-08-31 19:45 UTC, arthurwolf commented
Render of most recent version (with the health checks moved to the separate per-pod sections) of the operations page, for reference:

![Uploading Screenshot_2021-08-31 Operational procedures — Wire documentation(2).png…]()

2021-08-31 19:50 UTC, arthurwolf commented
TODO: Still need to do the "word of caution" section as instructed by @julialongtin :+1: 

```
« I would move the content into the sections (so people know how to health check), then move the "what to do about needing to reboot" stuff into a separate section, that says "perform health checks here, and here, and"...
and probably add a word of caution that one needs to actually understand these instructions, they are not guaranteed correct for every environment, you can destroy your data, yadda yadda..
"if you are unsure, contact your wire customer support representative", etc. »
```

2021-08-31 22:32 UTC, jschaul commented on src/how-to/administrate/cassandra.rst
> +Check the health of a Cassandra node
There is already a section `How to see cluster health` further up in this file. Maybe you can move this part up and merge? It's a good idea to give an example output though.

2021-08-31 22:32 UTC, jschaul commented on src/how-to/administrate/elasticsearch.rst
> +  kubectl port-forward svc/brig 9999:8080
```suggestion
  # The following depends on your namespace where you installed wire-server. By default the namespace is called 'wire'.
  kubectl --namespace wire port-forward svc/brig 9999:8080 
```

2021-08-31 22:32 UTC, jschaul commented on src/how-to/administrate/operations.rst
> +The general procedure to reboot a pod is as follows:
We need to discuss terminology here. `pod`s only exist inside kubernetes. In quite a few installations, cassandra/elasticsearch/redis are installed on virtual machines / servers directly, not inside kubernetes. So they cannot be called a `pod`. Manual healthchecks make sense mostly for the things *outside* kubernetes. 
`service` is not a good word to use, it has too many meanings. 

I would split this section by reboot procedures for virtual machines; and possibly pod restart procedures (though there is no rebooting, one deletes a pod and then it gets re-created by the deployment resource, so different terminology needs to be used).

Let's discuss this section in a call; there are too many changes that need to be done to this particular page, so commenting will be inefficient, a call will be easier.

2021-08-31 22:32 UTC, jschaul commented on src/how-to/administrate/restund.rst
> +Rebooting a Restund node
This procedure as described here will cause downtime, even if a second restund server is up; and kill any ongoing audio/video calls. The sections further up describe a downtime and a no-downtime procedure already. This requires a big warning note that if you do this restart; all calls will be interrupted.
Also this should be merged into the previous sections.

2021-08-31 22:37 UTC, arthurwolf commented on src/how-to/administrate/operations.rst
> +The general procedure to reboot a pod is as follows:
Yep I'm not surprised I'd mix up pod/service/server/node. I need to go over all of the files and make sure i'm using the right terms everywhere indeed.

2021-08-31 22:40 UTC, arthurwolf commented
@jschaul  Thanks a lot for all the notes, I'll go over them in the morning, try to follow everything as best as I can ( in particular do the merges you recommend ), and we can go over things based on that new/updated version in the call later in the day.

2021-08-31 22:41 UTC, arthurwolf commented on src/how-to/administrate/restund.rst
> +Rebooting a Restund node
It was my understanding that the instructions I was given (I'm just porting steps julia gave me) would not cause downtime (that it was their entire point). Maybe I misunderstood, or there's some kind of mistake somewhere. I'm asking julia, maybe she'll be able to clarify things.

2021-09-01 10:41 UTC, tjanson commented on src/how-to/administrate/elasticsearch.rst
> +Check the health of an ElastiSearch node
It's "Elasticsearch".

We're looking forward to the documentation improvements, by the way. Happy to see it. 👍

2021-09-01 14:08 UTC, arthurwolf commented
TODO: Fix the links so they are internal instead of external.

2021-09-01 14:16 UTC, arthurwolf commented
TODO: Make sure I use the right wording for pod/server/service everywhere.

2021-09-01 14:17 UTC, arthurwolf commented
TODO: Add a note that if a pod is running, it means it's healthy.

2021-09-01 14:26 UTC, arthurwolf commented
TODO: Get info on how to reboot servers from backend-wiki (dev/wire/backend-wiki*), and list them/import them

2021-09-18 17:13 UTC, julialongtin commented
hey, having to walk a customer through some of this, because this isn't yet published.
:grumble:

2021-09-19 16:20 UTC, arthurwolf commented on src/how-to/administrate/cassandra.rst
> +Check the health of a Cassandra node
Done.

2021-09-19 16:26 UTC, arthurwolf commented on src/how-to/administrate/operations.rst
> +The general procedure to reboot a pod is as follows:
I replaced most instances of "pods" with "services" because Julia needs this to be published now as it's needed for customers. It does make sense to clarify with better terms though, like you said. Please schedule a call when you have a bit of time, and we'll go over it, and I'll do a separate/new PR just for this.

2021-09-19 16:31 UTC, arthurwolf commented on src/how-to/administrate/restund.rst
> +Rebooting a Restund node
Done some of the instructed changes, still not clear what the difference is between restarting the service and rebooting, and why restarting it has a multi-step process if it drops calls anyway, but I added the warnings and moved the instructions around.

2021-09-19 16:33 UTC, arthurwolf commented on src/how-to/administrate/elasticsearch.rst
> +Check the health of an ElastiSearch node
fixed in a lot of places, thanks a lot for noticing

2021-09-19 16:40 UTC, merged