mention webapp environment variables for federation
wireapp/wire-docs pull request #230
Opened 2021-11-03 11:20 UTC by jschaul

Also mention the necessary configuration variables on the webapp for federation.

## Checklist:

Please tick the following before making your PR:

* [x] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [x] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.

2021-11-04 19:05 UTC, atomrc requested changes

2021-11-04 19:05 UTC, atomrc commented on src/how-to/install/configure-federation.rst
> +        FEATURE_ENABLE_DOMAIN_DISCOVERY: "true"
Not sure what is this `FEATURE_ENABLE_DOMAIN_DISCOVERY`. I do see it in the config but we never actually consume it in the app :shrug: 

Now we also need the 

`FEATURE_FEDERATION_DOMAIN`: 'example.com' `

For the federation feature to work in the webapp.

2021-11-04 19:05 UTC, atomrc commented on src/how-to/install/configure-federation.rst
> +        FEATURE_ENABLE_DOMAIN_DISCOVERY: "true"
```suggestion
        FEATURE_FEDERATION_DOMAIN: "example.com"
```

2021-11-08 16:24 UTC, jschaul commented
Thanks for the review @atomrc! I incorporated your suggested change.

2021-11-08 16:24 UTC, merged