add sftd docs
wireapp/wire-docs pull request #98
Opened 2021-01-14 13:17 UTC by arianvp

(fill in your PR description)

## Checklist:

Please tick the following before making your PR:

* [x] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [x] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.

2021-01-18 17:57 UTC, lucendio requested changes

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +of participants is limited by the upload bandwidth of the clients.
```suggestion
Previously, Wire group calls were implemented as a mesh, where each participant was connected
to each other in a peer-to-peer fashion. This meant that a client would have to upload their
video and audio feeds separately for each participant. This in practice meant that the amount
of participants was limited by the upload bandwidth of the clients.
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +
```suggestion

    helm upgrade --install sftd wire/sftd --set
    helm install sftd wire/sftd  \
      --set host=$SFTD_HOST \
      --set allowOrigin=https://$WEBAPP_HOST \
      --set-file tls.crt=/path/to/tls.crt \
      --set-file tls.key=/path/to/tls.k

```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +
```suggestion

Wire now has a signalling-forwarding unit called `SFT <https://github.com/wireapp/wire-avs-service>`_ which allows clients to upload once and
then the SFT fans it out to the other clients. Because connections are not end-to-end anymore now, dTLS encryption offered by WebRTC is not enough anymore as the encryption is terminated at the server-side. To avoid Wire from seeing the contents of calls SFT utilises WebRTC InsertibleStreams to encrypt the packets a second time with a group key that is not known to the server.

```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +Using SFT large but secure audio and video calls are possible.
question: what does the sentence mean? More precisely, *[..] large [...]*?

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +Only one SFT instance can run per node so if you want to scale up your SFT instance you will need to increase the amount of kubernetes nodes in your cluster.
question: is K8s already implicit at this point? or should *kubernetes nodes* rather be sth like *machines* or *servers*?

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +For more information about capacity planning and networking please refer to the technical documentation at https://github.com/wireapp/wire-server/blob/eab0ce1ff335889bc5a187c51872dfd0e78cc22b/charts/
```suggestion
For more information about capacity planning and networking please refer to the `technical documentation <https://github.com/wireapp/wire-server/blob/eab0ce1ff335889bc5a187c51872dfd0e78cc22b/charts/sftd/README.md>`_
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +The SFT component is shipped as a separate helm chart.  Installation is similar to installing
```suggestion
The SFT component is shipped as a separate helm chart. Installation is similar to installing
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +By default ``sftd`` doesn't need to set that many options so we define them inline. However you could of course also set these values in a ``values.yaml`` file.
```suggestion
By default ``sftd`` doesn't need to set that many options, so we define them inline. However, you could of course also set these values in a ``values.yaml`` file.
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +SFTD will deploy a kubernetes Ingress on ``$SFTD_HOST``.  Make sure that the domain name ``$SFTD_HOST`` points to your ingress IP as set up in :ref:`helm_prod`.   The SFTD also needs to be made aware
```suggestion
SFT will deploy a Kubernetes Ingress on ``$SFTD_HOST``.  Make sure that the domain name ``$SFTD_HOST`` points to your ingress IP as set up in :ref:`helm_prod`.  The SFT also needs to be made aware of the domain name of the webapp that you set up in :ref:`helm_prod` for setting up the appropriate CSP headers.
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +For more advanced setups please refer to the technical documentation at https://github.com/wireapp/wire-server/blob/eab0ce1ff335889bc5a187c51872dfd0e78cc22b/charts/sftd/README.md
```suggestion
For more advanced setups please refer to the `technical documentation <https://github.com/wireapp/wire-server/blob/eab0ce1ff335889bc5a187c51872dfd0e78cc22b/charts/sftd/README.md>`_
```

2021-01-18 17:57 UTC, lucendio commented on src/how-to/install/sft.rst
> +You should make sure that in ``values/wire-server/values.yaml`` you set  ``brig.optSettings.setSftStaticUrl`` to ``https://$SFTD_HOST:443`` where ``$SFTD_HOST`` is replaced with the domain name of th
question: any idea why this isn't a list of URLs?

2021-01-18 18:06 UTC, arianvp commented on src/how-to/install/sft.rst
> +Using SFT large but secure audio and video calls are possible.
I mean with more than 6 participants

2021-01-18 18:08 UTC, arianvp commented on src/how-to/install/sft.rst
> +Only one SFT instance can run per node so if you want to scale up your SFT instance you will need to increase the amount of kubernetes nodes in your cluster.
One could perfectly fine run multiple SFT instances on one server if you have multiple IPs; but kubernetes (at least in IPv4) does not give us this. So it's a kubernetes-specific issue.

2021-01-20 12:21 UTC, lucendio reviewed
(a leftover, sorry)

2021-01-20 12:21 UTC, lucendio commented on src/how-to/install/sft.rst
> +======================================================
```suggestion

Installing Conference Calling 2.0 (aka SFT)
======================================================
```

2021-01-20 12:40 UTC, arianvp commented on src/how-to/install/sft.rst
> +You should make sure that in ``values/wire-server/values.yaml`` you set  ``brig.optSettings.setSftStaticUrl`` to ``https://$SFTD_HOST:443`` where ``$SFTD_HOST`` is replaced with the domain name of th
This points to the load-balancer (nginx-ingress) of which we need and have one!  (The load-balancer will then route the request to one of the available SFT servers)

2021-01-20 13:06 UTC, merged

2021-01-26 17:50 UTC, lucendio commented on src/how-to/install/sft.rst
> +You should make sure that in ``values/wire-server/values.yaml`` you set  ``brig.optSettings.setSftStaticUrl`` to ``https://$SFTD_HOST:443`` where ``$SFTD_HOST`` is replaced with the domain name of th
Yeah okay. In the scenario of putting SFT on top of K8s, it's not an issue and not needed. But our own deployment atm has a couple of SFT instances and the `/calls/config.json return a list of SFTs - and we dont do LB there atm. I guess, what I'm trying to say is, being able to define a list instead of a single FQDN would just be consistent with on-prem TURN and how we do it currently. Anyway, I move the conversation and my confusion around this into the team.